### ISSUE TITLE
Did you forget to resolve a git conflict?

### ISSUE THREAD

**Issue by moble** [MarcPartensky/Fourier#1]
https://github.com/MarcPartensky/Fourier/blob/0e8213f9e259b3e747891a9e6bc0cbfb5bcb41a3/fourier_drawing/__init__.py#L1-L5

**Comment by moble** [comment]
It looks like there are more unresolved conflicts in these files:

```
.gitignore
README.md
fourier_drawing/__init__.py
fourier_drawing/context.py
fourier_drawing/draw.py
fourier_drawing/plane.py
fourier_drawing/plane.py
fourier_drawing/window.py
setup.py
```

**Comment by MarcPartensky** [comment]
Thanks a lot for noticing the conflicts! I pushed a working version without any of these.
