### ISSUE TITLE
a clean epicycle simulation

### ISSUE THREAD

**Issue by sfmth** [MarcPartensky/Fourier#2]
How do I simulate the epicycles just like the demo video?
I just want to make a video out of it without the image or the yellow drawing dots

**Comment by MarcPartensky** [comment]
If you want to make the simulation on your own image its is possible.
You need to provide the path of your image, or put it in the FourierImage folder and give its name as input when launching the program.

Then you will have to sample your image yourself by following the outline of your image and clicking point by point,
BUT before that you must clear the previous sample made by typing on 'R'.

Then you can press space to see the simulation.
Have fun!

**Comment by MarcPartensky** [comment]
If you want more information about controls you can see the `Controls` section down in the readme.

**Comment by sfmth** [comment]
Oh. I think you got me wrong. I know how to operate it but I want to have a mode in which the image and the drawing are not present. 
`elif self.mode == 1:
            if self.show_polynomial:
                self.drawPolynomial(drawing, self.color_polynomial)
            #if self.show_drawing:
            #    self.drawGraph(drawing, self.color_drawing)
            if self.show_vectors:
                self.drawVectors(construction, self.color_vectors)
            if self.show_circles:
                self.drawCircles(construction, self.color_circles)
            if self.show_display:
                self.drawGraph(display, self.color_display)
            #if self.show_sample:
            #   self.drawPoints(self.sample, self.color_sample)`
I did this now I get what I want. but still the image is shown, but I just loaded an empty image now it works fine. You might wanna add another mode ...

**Comment by MarcPartensky** [comment]
All right, I think i get it.
Actually it is possible to hide the image and the drawing by using the numbers in the range of 0 to 6.
* You can hide the image by pressing `1`
* You can hide the drawing by pressing `3`

As you can see, with this system there is no need for another mode.
I just forgot to put it in the controls section in the readme, so thanks for noticing!

**Comment by sfmth** [comment]
Oh, that's great good job
