### ISSUE TITLE
Missing FourierObject/fourier

### ISSUE THREAD

**Issue by CharlesLiangZHY** [MarcPartensky/Fourier#5]
I followed the README to run your code. But it seems that the config file is missing. The idea of the project is great. I am really wondering how you implement the extraction of outline of people in the image. I try to read your code, but I did not find it.

**Comment by MarcPartensky** [comment]
Hi don't worry once I fix the bug you will see how to sample points from the image. You just have to click where you want to add a sample point to draw the picture. It is very intuitive.

**Comment by MarcPartensky** [comment]
Fixed ! It is not trying to load non-existent coefficients anymore when used for the first time.
