### ISSUE TITLE
Video system could not be initialized

### ISSUE THREAD

**Issue by TopHatGamer15** [MarcPartensky/Fourier#6]
I would like to try this out but upon loading it into windows ubuntu
python3 ./Fourier/__main__.py saint jalm.jpg
 
it just gives me this error 

pygame 2.1.0 (SDL 2.0.16, Python 3.8.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
path: /home/hunter/FourierImages/saint
[Application of the Fourier Transform.] Window has been created.
Traceback (most recent call last):
  File "./Fourier/__main__.py", line 27, in <module>
    context = Context(name="Application of the Fourier Transform.", fullscreen=False)
  File "/home/hunter/Fourier/fourier_drawing/context.py", line 418, in __init__
    draw = Draw(**kwargs)
  File "/home/hunter/Fourier/fourier_drawing/draw.py", line 35, in __init__
    window = Window(**kwargs)
  File "/home/hunter/Fourier/fourier_drawing/window.py", line 49, in __init__
    self.build(size)
  File "/home/hunter/Fourier/fourier_drawing/window.py", line 65, in build
    self.info = pygame.display.Info()
pygame.error: video system not initialized

Its possible i'm just missing something but I have spent a couple of hours just getting here since for whatever reason nothing wanted to install properly.

**Comment by MarcPartensky** [comment]
Hi are you sure you can use sdl2 at all inside of wsl ubuntu?

**Comment by MarcPartensky** [comment]
It seems to me that in order to add a graphical display out of wsl there is extra work to do with the wsl configuration.

**Comment by MarcPartensky** [comment]
It might be possible to use a vncserver display to get arround the issue.
